In [ ]:
import numpy as np
import time

In [ ]:
# creating arrays using built in methods
arr3=np.zeros((2,3), dtype="int64")#prefill
print(arr3, arr3.shape)

arr4=np.ones((5,),dtype="int64")
print(arr4, arr4.shape)

arr5=np.full((2,3),20)
print(arr5,arr5.dtype,arr5.shape)

# creationg identity matrix
arr6=np.eye(3,dtype="int64")
print(arr6,type(arr6),arr6.shape,arr6.dtype)

# arr in range with jump by 2
arr7=np.arange(0,11,2)
print(arr7,arr7.shape)

# evenly spaced array
arr8=np.linspace(0,20,6,dtype="int64") #linspace(start,end,no of elements)
print(arr8)

[[0 0 0]
 [0 0 0]] (2, 3)
[1 1 1 1 1] (5,)
[[20 20 20]
 [20 20 20]] int64 (2, 3)
[[1 0 0]
 [0 1 0]
 [0 0 1]] <class 'numpy.ndarray'> (3, 3) int64
[ 0  2  4  6  8 10] (6,)
[ 0  4  8 12 16 20]


In [ ]:
a=np.ones((2,3))
print(a)
b=np.arange(0,10,2)
print(b)
c=np.linspace(0,100,6)
print(c)
print(c,c.ndim,c.dtype,c.shape,c.size)
intc=c.astype("int32")#define data type
print(intc.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[  0.  20.  40.  60.  80. 100.]
[  0.  20.  40.  60.  80. 100.] 1 float64 (6,) 6

int32


In [ ]:
# indexing on numpy arrays
arr = np.array([1,2,3,4,5,6,7])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[-1])
# indexing in 2d arrays
arr1=np.array([[1,2,3,0],[4,5,6,1],[7,8,9,2]])
print(arr1[0,2])
# doing fancy indexing
idx=[1,3,5]
print(arr[idx])
# boolean indexing
print(arr[arr>4])
# slicing array
print(arr[0:5:2])
# slice step needs to be understood
print(arr1[1:3,2:4])

1
2
3
7
3
[2 4 6]
[5 6 7]
[1 3 5]
[[6 1]
 [9 2]]


In [ ]:
a=np.array([1,2,3])
b=a.copy() #if anything changed in b then does not effect a
b[0]=100
c=a
c[0]=200 #changing in c affects a
print(a)
print(b)
print(c)

[200   2   3]
[100   2   3]
[200   2   3]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a%b)
print(a//b)
print(a+10)
print(a*2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[1 2 3]
[0 0 0]
[11 12 13]
[2 4 6]


In [ ]:
a=np.array([1,4,9,16])
print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.sum(a))
print(np.std(a))#standard deviation

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
1
7.5
30
5.678908345800274


In [ ]:
a=np.array([10,20,30,40,50,60,70])
print(a[a>25])
print(a>25)

[30 40 50 60 70]
[False False  True  True  True  True  True]


In [ ]:
#Element wise multiplication: The Pytho * operator does not sum the results It maintains the shape
#Broadcasting: describes how numpy treats arrays with different shapes during arithmetic operations. The smaller array is "broadcast" stretched across the larger array so that they have compatible shapes.
#Outer Product
# 1                1 1 1    10 20 30
# 2 + [10 20 30] = 2 2 2 +  10 20 30
# 3                3 3 3    10 20 30

#Scalar Scaling [One dim is 1]
#Broadcasting Documentation
#Trailing Dimension Mismatch (Column does nto fit)
#Row Mismatch : Ambiguous Expansion (2,2) (3,2)
#Element wise multiplication

In [ ]:
#Broadcasting Rule: NumPy automatically expands smaller arrays

In [2]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr+10)

[11 12 13 14]


In [4]:
mat=np.array([[1,2,3],[4,5,6]])
print(mat+10)

[[11 12 13]
 [14 15 16]]


In [5]:
row=np.array([1,2,3])
print(mat+row)

[[2 4 6]
 [5 7 9]]


Matrix Multiplication

In [6]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(np.dot(A,B))


[[19 22]
 [43 50]]


In [7]:
print(A.T)#transpose

[[1 3]
 [2 4]]


Random Module

In [8]:
np.random.rand(5)

array([0.88976139, 0.41857183, 0.19668804, 0.04123156, 0.11177324])

In [9]:
np.random.rand(3,3)#(rows,columns)

array([[0.94587664, 0.73269257, 0.63010444],
       [0.39024551, 0.87988775, 0.05468034],
       [0.10169904, 0.23258313, 0.86100668]])

In [10]:
np.random.randint(1,100,10)#(start,end,total number)

array([64, 45, 29, 25, 46, 78, 20, 40, 72, 19])

In [13]:
arr=np.arange(12)
print(arr.reshape(3,4))#(rows,columns)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Access In NumPy

In [14]:
arr=np.array([[1,2,3,],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
print(np.sum(arr))

21


In [16]:
print(np.sum(arr,axis=0))#sums the columns

[5 7 9]


In [17]:
print(np.sum(arr,axis=1))#sums the rows

[ 6 15]


Where in NumPy

In [18]:
arr=np.array([10,-5,20,-3,15])
result=np.where(arr<0,0,arr)#(condition,replace with,name of array)
print(result)

[10  0 20  0 15]


In [19]:
arr=np.array([1,2,3,4,5])
result=np.where(arr%2!=0,-1,arr)
print(result)

[-1  2 -1  4 -1]


In [20]:
marks=np.array([45,78,32,90,55])
status=np.where(marks>=50,1,0)
print(status)

[0 1 0 1 1]


In [21]:
data=np.array([10,20,30,40,50])
mean=np.mean(data)
result=np.where(data>mean,mean,data)
print(result)

[10. 20. 30. 30. 30.]


Apply Where Condition in 2D Array

In [22]:
mat=np.array([[10,60,30],[80,20,90]])
result=np.where(mat>=50,1,0)
print(result)

[[0 1 0]
 [1 0 1]]
